language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: "EMAIL_ADDRESS"
  api_key: "NPM_AUTH_TOKEN"
  on:
    tags: true
    branch: master
env:
  global:
  - secure: A8siFVhaOV9S7iwfX7xJI/i6TkzyG33M25IbOY5Bentul44+ewUb5hEwBKVIE1L/Kt+HlQTSXc1APwutRVyBDZusUb/BaBoa6tSqEJw+iwAnn1ITgWYu1ChzJsB2NQ4g8octW5yYM85fJYYB7RNLWYnan4u8drnWnt4YWS5UFGPl56oDWPmBQu30+nU9c0XwUwuv88ly5L3dh6sx3mmwz7apaNywOMhrpfoKerjjHq/SdTnM8C1WcltOedP1t5nzYzXcHwcb9k1uL8OidshHY8CfUF6wjYUUeP6EIYf87zwKbWmQCVolorSa0tmnk9lnVefse3QZfxJw4SMVchLvrAlbFn2gAXtxuOtoSbG4VAVj2oZha3FA6kuV+cQVOOksSaTgdfkCEnKpqLbjuobJi//6AvLsrDOpkLjHOoBPuP+Nn4m80vNSGQDPY+Lbr17X02FcUJs+C7g0tcHcp4Nk8DVLPIkVWBNyNrtsQR9Nc8+wFCpekXkz513r9s2W/8jqNDpmXR6fg6qJ1ehZuaE3UDWIgZyJQVaH3dl9tphVpZ8irKliElmVVqzIxDehbnXqZqL0DLB/lQJ6t+bqsvpHW4IcNPW5SWeN5js5v9YAQ+AEGXDHrFqoS8XwyutBYU1qGk8xkXmLX9ucTUkrOtLxcaatv6f2Nl1zgaXHF4h7Emo=
  - secure: UuNHXGKkHfcoPbU7WfiuhWZpkCczVpUoaFdVcUwTLSmdAm/+QfBK49Hl78+mmHq1TDQphRbWqDb9tIyUExK6W0CsXes0TDQ+BxX1KKIpwBu0ifIWRIn6iJJLvVgv7rwZzSGcNbroUkEjvQ+9TnuZ+Rr41Pe+4RhF3BJ8UWGFVzDhpgsxeosnUS4egZTru+wbF7kY3uy7OlA6TVUyoXk1oy6Ds227cFZTpqIE2bI2Gmeq8vGyYPGBvIt8RlhXIphG7XDtXKplWmmB4ThIWcxJdRj3V6S3vl+bVf2FpCJYqBecLZtdhbTAe/1LkJequ42swk6/AkBs7z8NfmbZp54d6WoETqEWgRI6ryOVqnVdOSSm4fHtbERjFe848Shsaost8gp4n88GuOgyah8wYwDnBrmxHllY/dziZcBfjTxA55q0RQUrhD3iqHgkDOOVDPCFjBMBCZ9nDwjGRYkhkXEgPyyPgwres5dQCx11E3LV+qxRE96xLjIusYrLPPMktgO6+/WBmaScbPPjr4Jl3+bMWjnWLA+xYDYBpKOwd0faWxALX3fIx95LuFHpY5gt1sqaJB7iq/wtd7se5K+m5f3/yMdeoIPy7wFj9Gn4KUWUA17KuM9Rg4ifnFvdlYV4R+/9LckYteVAWohlLBQXtcXqCBGocz0iqlMnj7Jd4wnMxVE=
