# name: pr-validation
# on:
#   pull_request:
#     branches:
#       - master
#       - next

# jobs:
#   build-nact:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: 15
#       - run: npm install
#       - run: npm run build --if-present
#       - run: npm test
#         env:
#           CI: true
